# 智能网络转发器配置文件
# 支持TCP、HTTP、UDP协议转发
# 支持动态地址更新和故障转移

logging:
  level: "info"
  format: "json"

network:
  listen_addr: "0.0.0.0"

# 全局缓冲区大小设置 (8KB，适合大多数应用)
buffer_size: 8192

# 转发规则配置
rules:
  # HTTPS转发规则
  - name: "HTTPS"
    listen_port: 443
    protocol: "tcp"    # 单独指定TCP协议（HTTPS只需要TCP）
    buffer_size: 4096     # HTTPS专用缓冲区 (4KB，较小的请求响应)
    targets:
      - "192.168.5.254:443"
      - "121.40.167.222:50443"
      - "stun-443.4.ipto.top"      
  # RDP转发规则
  - name: "RDP"
    listen_port: 99
 #   protocol: "tcp" 
    buffer_size: 16384    # RDP UDP专用大缓冲区 (64KB，适合视频流)
    targets:
      - "192.168.5.12:3389"
      - "121.40.167.222:57111"
      - "ewin10.4.ipto.top"      
  # 网盘转发规则
  - name: "Drive"
    listen_port: 6690
    protocol: "tcp"    # 网盘只需要TCP协议
    buffer_size: 32768    # 网盘专用大缓冲区 (32KB，文件传输需要)
    targets:
      - "192.168.5.3:6690"
      - "121.40.167.222:6690"
      - "drive.4.ipto.top"  # 纯域名，通过TXT记录解析      

  - name: "tRDP"
    listen_port: 999
    protocol: "tcp" 
    buffer_size: 16384    # RDP UDP专用大缓冲区 (64KB，适合视频流)
    targets:
      - "ewin10.4.ipto.top"     

  - name: "uRDP"
    listen_port: 999
    protocol: "udp" 
    buffer_size: 16384    # RDP UDP专用大缓冲区 (64KB，适合视频流)
    targets:
      - "uewin10.4.ipto.top"          