# 智能网络转发器配置文件
# 支持TCP、HTTP、UDP协议转发
# 支持动态地址更新和故障转移

logging:
  level: "info"
  format: "json"

network:
  listen_addr: "0.0.0.0"

# 全局缓冲区大小设置 (8KB，适合大多数应用)
buffer_size: 8192

# 转发规则配置
rules:
  # HTTPS转发规则
  - name: "HTTPS"
    listen_port: 443
    protocol: "tcp"    # 单独指定TCP协议（HTTPS只需要TCP）
    buffer_size: 4096     # HTTPS专用缓冲区 (4KB，较小的请求响应)
    targets:
      - "192.168.5.254:443"
      - "stun-443.4.ipto.top"      
      - "121.40.167.222:50443"

  # RDP转发规则
  - name: "RDP"
    listen_port: 99
    # 默认同时支持TCP和UDP协议，无需指定 protocols
    # protocols: ["tcp", "udp"]  # 可选：只有需要自定义时才指定
    buffer_size: 16384    # RDP专用缓冲区 (16KB，平衡性能和内存)
    targets:
      - "192.168.5.12:3389"
      - "ewin10.4.ipto.top"
      - "121.40.167.222:57111"

  # 网盘转发规则
  - name: "Drive"
    listen_port: 6690
    protocol: "tcp"    # 网盘只需要TCP协议
    buffer_size: 32768    # 网盘专用大缓冲区 (32KB，文件传输需要)
    targets:
      - "192.168.5.3:6690"
      - "drive.4.ipto.top"  # 纯域名，通过TXT记录解析      
      - "121.40.167.222:6690"

  # STUN穿透示例（默认TCP+UDP）
  - name: "STUN"
    listen_port: 999
    # 默认同时支持TCP和UDP，无需指定协议
    buffer_size: 4096    # STUN协议消息较小，4KB足够
    targets:
      - "112.10.240.87:7853"
      - "stun-server.example.com:999"

