version: '3.8'

services:
  smart-forward:
    image: smart-forward:latest
    container_name: smart-forward
    restart: unless-stopped
    network_mode: host
    volumes:
      - "./config.yaml:/app/config.yaml:ro"
    environment:
      - RUST_LOG=info
      - TZ=Asia/Shanghai
