version: '3.8'

services:
  smart-forward:
    image: smart-forward:latest
    container_name: smart-forward-container
    restart: unless-stopped
    
    # 端口映射 - 根据配置文件调整
    ports:
      - "443:443"   # HTTPS 服务
      - "99:99"     # RDP 服务 (TCP+UDP)
      - "6690:6690" # 网盘服务
      - "999:999"   # 分离式RDP (TCP+UDP)
    
    # 挂载配置文件
    volumes:
      - "./config.yaml:/app/config.yaml:ro"
      - "./logs:/app/logs"  # 日志目录 (可选)
    
    # 环境变量
    environment:
      - RUST_LOG=info
      - TZ=Asia/Shanghai
    
    # 健康检查
    healthcheck:
      test: ["/usr/local/bin/smart-forward", "--validate-config"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # 网络配置
    networks:
      - smart-forward-net
    
    # 资源限制 (可选)
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'

networks:
  smart-forward-net:
    driver: bridge
