# OpenWrt 测试配置文件
# 测试多监听地址和动态配置功能

logging:
  level: "info"
  format: "text"  # OpenWrt推荐text格式

# 多监听地址测试
network:
  listen_addrs:
    - "192.168.1.1"    # 主LAN地址
    - "10.0.0.1"       # 可能的第二网络

# 缓冲区配置
buffer_size: 8192

# 动态更新配置测试
dynamic_update:
  check_interval: 3       # 3秒检查间隔
  connection_timeout: 1   # 1秒连接超时
  auto_reconnect: true    # 自动重连

# 测试规则
rules:
  - name: "HTTP_Test"
    listen_port: 8080
    protocol: "tcp"
    targets:
      - "httpbin.org:80"
      - "example.com:80"
      
  - name: "DNS_Test"
    listen_port: 8053
    # 默认tcp+udp协议
    targets:
      - "1.1.1.1:53"
      - "8.8.8.8:53"
      
  - name: "HTTPS_Test"
    listen_port: 8443
    protocol: "tcp"
    targets:
      - "www.google.com:443"
      - "www.baidu.com:443"
