# Docker Compose with macvlan network
# 解决 80/443 端口冲突问题，给容器分配独立IP
version: '3.8'

services:
  smart-forward:
    image: ghcr.io/cls3389/smart-forward:latest
    container_name: smart-forward
    restart: unless-stopped
    
    # 使用 macvlan 网络，容器获得独立IP
    networks:
      macvlan_network:
        ipv4_address: 192.168.1.100  # 修改为您网络中可用的IP
    
    # 挂载配置文件
    volumes:
      - "./config.yaml:/app/config.yaml:ro"
      - "logs:/app/logs"
    
    # 环境变量
    environment:
      - RUST_LOG=info
      - TZ=Asia/Shanghai
    
    # 健康检查
    healthcheck:
      test: ["CMD", "/usr/local/bin/smart-forward", "--validate-config"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# macvlan 网络配置
networks:
  macvlan_network:
    driver: macvlan
    driver_opts:
      parent: eth0  # 修改为您的网卡名称 (如 ens33, enp0s3 等)
    ipam:
      config:
        - subnet: 192.168.1.0/24      # 修改为您的网络段
          gateway: 192.168.1.1        # 修改为您的网关
          ip_range: 192.168.1.100/32  # 容器IP范围

volumes:
  logs:
    driver: local
