# 智能转发器配置文件

logging:
  level: "info"
  format: "text"

network:
  listen_addr: "0.0.0.0"

# 全局缓冲区大小（字节）
buffer_size: 8192

# 新增：动态地址更新配置
dynamic_update:
  # 检查地址更新的间隔（秒）
  check_interval: 30
  # 连接超时时间（秒）
  connection_timeout: 300
  # 是否启用自动重连
  auto_reconnect: true
  # 健康检查间隔（秒）
  health_check_interval: 60

rules:
  - name: "HTTPS"
    listen_port: 443
    targets:
      - "192.168.5.254:443"
      - "hz.ipto.top:50443"
    # 新增：规则级别的动态更新配置
    dynamic_update:
      enabled: true
      check_interval: 30  # 覆盖全局配置

  - name: "RDP"
    listen_port: 99
    buffer_size: 32768    # RDP专用缓冲区 (32KB)
    targets:
      - "192.168.5.12:3389"
      - "hz.ipto.top:57111"
    dynamic_update:
      enabled: true
      check_interval: 15  # RDP连接更敏感，更频繁检查

  - name: "Drive"
    listen_port: 6690
    buffer_size: 32768 
    targets:
      - "192.168.5.3:6690"
      - "hz.ipto.top:6690"
      - "drive.4.ipto.top"
    dynamic_update:
      enabled: true
      check_interval: 45  # 文件传输可以稍慢一些
