# 智能转发器配置文件

logging:
  level: "info"
  format: "text"

network:
  listen_addr: "0.0.0.0"

# 全局缓冲区大小（字节）
buffer_size: 8192

rules:
  - name: "HTTPS"
    listen_port: 443
    targets:
      - "192.168.5.254:443"
      - "hz.ipto.top:50443"

  - name: "RDP"
    listen_port: 99
    buffer_size: 32768    # RDP专用缓冲区 (32KB)
    targets:
      - "192.168.5.12:3389"
      - "hz.ipto.top:57111"

  - name: "Drive"
    listen_port: 6690
    buffer_size: 32768 
    targets:
      - "192.168.5.3:6690"
      - "hz.ipto.top:6690"
      - "drive.4.ipto.top"
